name: github pages

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu,wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - uses: cargo-bins/cargo-binstall@main
      - name: Install CLI
        run: cargo install --git https://github.com/ealmloff/dioxus --branch fix-static-generation dioxus-cli
      - name: Build
        run: dx serve --release --features fullstack --server-feature prebuild
      - name: Rebuild with search index
        # rebuild with the new search index
        run: dx serve --release --features fullstack --server-feature prebuild
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          target-folder: .
          clean: true # don't scrub docs
